project:
  name: quickstart-gitlab
  shorten_stack_name: true
  template: templates/gitlab-entry-new-vpc.template.yaml
  parameters:
    KeyPairName: taskcat-keypair
    RemoteAccessCIDR: 10.0.0.0/16
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages

tests:
  deploy-in-3-az-with-defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
      DBUserPassword: 'Ae6ii5fcckj4ddi0t!'
      DomainName: devops.$[taskcat_random-string].com
    regions:
    - eu-west-1
