project:
  name: quickstart-eks-gitlab
  shorten_stack_name: true
  template: templates/gitlab-entry-new-vpc.template.yaml
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  package_lambda: true
  lambda_source_path: functions/source
  lambda_zip_path: functions/packages
  build_submodules: true
  s3_regional_buckets: true

tests:

  deploy-in-3-az-with-defaults:
    parameters:
      AvailabilityZones: $[taskcat_genaz_3]
      NumberOfAZs: 3
      EKSPublicAccessEndpoint: Enabled
      ProvisionBastionHost: Disabled
      DomainName: devops.$[taskcat_random-string].com
      RDSDBInstanceClass: db.t3.small
    regions:
      - eu-west-1
      - us-east-1
      - us-west-2

  deploy-in-2-az-with-optional-features:
    parameters:
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      EKSPublicAccessEndpoint: Disabled
      ProvisionBastionHost: Enabled
      DomainName: devops.$[taskcat_random-string].com
      ConfigureContainerInsights: 'Yes'
      ConfigureGrafana: 'Yes'
      CacheMode: External
      PublicDNS: CreateNew
      SMTPDomain: CreateNew
      ConfigureRunner: 'Yes'
      PrivilegedMode: 'Yes'
      RDSDBInstanceClass: db.t3.small
    regions:
      - eu-central-1

#Gitaly must be set to 3 instances
#technically running graviton RDS and Elasticache could
#still be considered x86 because these are PaaS
  smallest-possible-x86:
    parameters:
      GitLabVersion: 14.10.5
      HelmChartVersion: 5.10.5
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      EKSPublicAccessEndpoint: Disabled
      ProvisionBastionHost: Enabled
      DomainName: --override--
      CreateSslCertificate: 'Yes'
      SslCertificateIssuerEmail: gitlab@$[taskcat_random-string].com
      ConfigureContainerInsights: 'Yes'
      ConfigureGrafana: 'Yes'
      SMTPDomain: CreateNew
      ConfigureRunner: 'No'
      PriviligedMode: 'No'
      NumberOfNodes: 2
      NodeInstanceType: t3.medium
      RDSDBInstanceClass: db.t3.small
      CacheMode: External
      CacheNodes: 2
      CacheNodeType: cache.t3.small
      NumberOfGitalyReplicas: 3
      GitalyInstanceType: t3a.small
      NumberOfPraefectReplicas: 3
      PraefectInstanceType: t3a.micro
      KeyPairName: eks-quickstart
      GitalyPraefectInstanceArchitecture: x86_64
    regions:
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - us-east-1
      - us-west-2

#The cluster cannot use ARM yet - must specific x86 instances.
#Gitaly must be set to 3 instances
#14.9.0 is the first release that has ARM packages for AL2.
#Do this on the console (region and AZs set for us-east-2) and fix up any parameters set to SUBSTITUTE_YOUR_ACTUAL_VALUE: https://us-east-2.console.aws.amazon.com/cloudformation/home?region=us-east-2#/stacks/quickcreate?templateUrl=https://aws-quickstart.s3.us-east-1.amazonaws.com/quickstart-eks-gitlab/templates/gitlab-entry-new-vpc.template.yaml&stackName=GitLabCostConstrainedSpot2AZst&param_NumberOfAZs=2&param_AvailabilityZones=us-east-2b,us-east-2c&param_NodeInstanceType=t3.medium&param_NumberOfNodes=2&param_MaxNumberOfNodes=3&param_DBInstanceClass=db.t4g.small&param_CacheNodes=2&param_CacheNodeType=cache.t4g.small&param_GitalyInstanceType=t4g.small&param_NumberOfGitalyReplicas=3&param_PraefectInstanceType=t4g.micro&param_NumberOfPraefectReplicas=3&param_GitalyPraefectInstanceArchitecture=arm64&param_ProvisionBastionHost=Enabled&param_RemoteAccessCIDR=198.51.100.0/24&param_KeyPairName=eks-quickstart&param_CreateSslCertificate=Yes&param_SslCertificateIssuerEmail=dsanoy@gitlab.com&param_SMTPDomain=CreateNew&param_RDSDBEngineVersion=12.11&param_GitLabVersion=15.4.1&param_HelmChartVersion=6.4.1&param_PublicDNS=UseExisting&param_PublicHostedZoneId=SUBSTITUTE_YOUR_ACTUAL_VALUE&param_DomainName=SUBSTITUTE_YOUR_ACTUAL_VALUE
  smallest-possible-arm-spot:
    parameters:
      OnDemandPercentage: 0 #100% spot EKS cluster
      GitLabVersion: 15.4.1
      HelmChartVersion: 6.4.1
      AvailabilityZones: $[taskcat_genaz_2]
      NumberOfAZs: 2
      EKSPublicAccessEndpoint: Disabled
      ProvisionBastionHost: Enabled
      CreateSslCertificate: 'Yes'
      SslCertificateIssuerEmail: gitlab@$[taskcat_random-string].com
      ConfigureContainerInsights: 'Yes'
      ConfigureGrafana: 'Yes'
      PublicDNS: UseExisting
      PublicHostedZoneId: --override--
      DomainName: --override--
      SMTPDomain: CreateNew
      ConfigureRunner: 'No'
      PriviligedMode: 'No'
      NumberOfNodes: 2
      NodeInstanceType: t3.medium
      RDSDBInstanceClass: db.t4g.small
      CacheMode: External
      CacheNodes: 2
      CacheNodeType: cache.t4g.small
      NumberOfGitalyReplicas: 3
      GitalyInstanceType: t4g.small
      NumberOfPraefectReplicas: 3
      PraefectInstanceType: t4g.micro
      KeyPairName: eks-quickstart
      GitalyPraefectInstanceArchitecture: arm64
    regions:
      - ap-south-1
      - ca-central-1
      - eu-central-1
      - eu-west-1
      - us-east-1
      - us-west-2
