AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Deploys Lambda functions required for the AWS GitLab Quick Start.
  (qs-1rpegts3l)

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W9002
        - W9003
        - W9004

Parameters:
  QSS3BucketName:
    Type: String
  QSS3KeyPrefix:
    Type: String

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, aws-quickstart]

Resources:

  CopyZips:
    Type: Custom::CopyZips
    Properties:
      ServiceToken: !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:${AWS::AccountId}:function:eks-quickstart-CopyZips
      SourceBucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      DestBucket: !Sub eks-quickstart-lambdazips-${AWS::Region}-${AWS::AccountId}
      Prefix: !Ref QSS3KeyPrefix
      Objects:
        - functions/packages/CfnSesDomain/lambda.zip
        - functions/packages/CleanupACMDNSValidation/lambda.zip
        - functions/packages/RandomString/lambda.zip
        - functions/packages/SmtpPasswordGenerator/lambda.zip
        - functions/packages/UpdateDnsRecord/lambda.zip

  RandomStringRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Sid: AssumeLambdaExecutionRole
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Sub arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  RandomStringFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Generates a random string.
      Handler: index.handler
      Timeout: 30
      Role: !GetAtt RandomStringRole.Arn
      Runtime: python3.9
      Code:
        S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
        S3Key: !Sub ${QSS3KeyPrefix}functions/packages/RandomString/lambda.zip

Outputs:
  FunctionsBucketName:
    Value: !Sub eks-quickstart-lambdazips-${AWS::Region}-${AWS::AccountId}
  RandomStringFunctionArn:
    Value: !GetAtt RandomStringFunction.Arn
