# https://github.com/awslabs/serverless-application-model/blob/develop/versions/2016-10-31.md
AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Deploys Gitlab Runner chart. (qs-1rpegts7g)

Metadata:
  cfn-lint:
    config:
      ignore_checks:
        - W9002
        - W9003
        - W9004

Parameters:
  ClusterName:
    Type: String
  HelmChartNamespace:
    Type: String
  HelmChartName:
    Type: String
  HelmChartVersion:
    Type: String
  DomainName:
    Type: String
  RunnerRegistrationToken:
    Type: String
    NoEcho: true
  RunnerImage:
    Type: String
  TlsCASecretName:
    Type: String
  MaximumConcurrentJobs:
    Type: Number
  PrivilegedMode:
    Type: String
    AllowedValues: ['true', 'false']

Resources:

  GitLabChart:
    Type: AWSQS::Kubernetes::Helm
    Properties:
      ClusterID: !Ref ClusterName
      Namespace: !Ref HelmChartNamespace
      Repository: https://charts.gitlab.io/
      Chart: gitlab/gitlab-runner
      Name: !Ref HelmChartName
      Version: !Ref HelmChartVersion
      ValueYaml: !Sub |
        gitlabUrl: https://gitlab.${DomainName}/
        runnerRegistrationToken: ${RunnerRegistrationToken}

        ## Configure the maximum number of concurrent jobs
        concurrent: ${MaximumConcurrentJobs}

        certsSecretName: ${TlsCASecretName}

        ## For RBAC support:
        rbac:
          create: true

        ## Configuration for the Pods that the runner launches for each new job
        ##
        runners:
          config: |
            [[runners]]
              clone_url = "https://gitlab.${DomainName}/"

              [runners.kubernetes]
                image = "${RunnerImage}"

                ## Run all containers with the privileged flag enabled
                ## This will allow the docker:stable-dind image to run if you need to run Docker
                ## commands. Please read the docs before turning this on:
                ## ref: https://docs.gitlab.com/runner/executors/kubernetes.html#using-docker-dind
                privileged = ${PrivilegedMode}

                ## Namespace to run Kubernetes jobs
                namespace = "${HelmChartNamespace}"

###
### Example of the pipeline that uses DIND to build and push the image to GitLab registry
### Note a trick with CA certificate for DIND container. Not needed for real TLS certs.
###

# .use-docker-in-docker:
#   variables:
#     #DOCKER_BUILDKIT: "1"
#     #DOCKER_DRIVER: overlay2
#     DOCKER_HOST: tcp://docker:2375
#     DOCKER_TLS_CERTDIR: ""
#     CA_CERTIFICATE: "$CA_CERTIFICATE"
#   image: docker:19.03.13
#   services:
#     # The following trick is needed to ensure that docker trusts self-signed certificate
#     - name: docker:19.03.13-dind
#       alias: docker
#       command:
#         - /bin/sh
#         - -c
#         - echo "$CA_CERTIFICATE" > /usr/local/share/ca-certificates/gitlab-ca.crt && update-ca-certificates && dockerd-entrypoint.sh || exit

# docker-build-master:
#   extends: [ .use-docker-in-docker ]
#   stage: build
#   before_script:
#     - echo $CA_CERTIFICATE
#     - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#   script:
#     - docker build --pull -t "$CI_REGISTRY_IMAGE" .
#     - docker push "$CI_REGISTRY_IMAGE"
#   only:
#     - master
