AWSTemplateFormatVersion: 2010-09-09
Description: Gitlab s3 Buckets

Parameters:
# Quickstart location Parameters
  QSS3BucketName:
    Type: String
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
  QSS3BucketRegion:
    Type: String
    Default: 'us-east-1'
    Description: 'The AWS Region where the Quick Start S3 bucket (QSS3BucketName) is hosted. 
      When using your own bucket, you must specify this value.'
  QSS3KeyPrefix:
    Type: String
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters, 
      uppercase letters, hyphens (-), and forward slash (/).
    Default: quickstart-examples/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).

# Infra Parameters
  DomainName:
    Type: String
    Description: The Domain name for the gitlab server.
  RealDomainName:
    Type: String
    Default: 'No'
    AllowedValues: [ 'Yes', 'No' ]
  CreateHostedZone:
    Type: String
    AllowedValues: [ 'Yes', 'No' ]
    Default: 'No'
  CreateEmailDomain:
    Type: String
    AllowedValues: [ 'Yes', 'No' ]
    Default: 'No'
  CreateSslCertificate:
    Type: String
    AllowedValues: [ 'Yes', 'No' ]
    Default: 'No'

# Network Parameters
  VPCID: 
    Description: "ID of the VPC you are deploying Aurora into (e.g., vpc-0343606e)."
    Type: 'AWS::EC2::VPC::Id'
  VPCCIDR:
    Type: String
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Description: CIDR block for the VPC.
  PrivateSubnet1ID:
    Description: The ID of the private subnet in Availability Zone 1.
    Type: 'AWS::EC2::Subnet::Id'
  PrivateSubnet2ID:
    Description: The ID of the private subnet in Availability Zone 2.
    Type: 'AWS::EC2::Subnet::Id'

# Cluster Parameters
  KubeClusterName:
    Type: String

# Databse Parameters
  DBName: 
    AllowedPattern: "[a-zA-Z0-9]*"
    Description: "Name of the Amazon Aurora database."
    MaxLength: "64"
    MinLength: "0"
    Default: gitlab
    Type: String
  DBPraefectName: 
    AllowedPattern: "[a-zA-Z0-9]*"
    Description: "Name of the Amazon Aurora database."
    MaxLength: "64"
    MinLength: "0"
    Default: praefect
    Type: String    
  DBMasterUsername: 
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]*"
    ConstraintDescription: "Must begin with a letter and contain only alphanumeric characters."
    Default: gitlab
    Description: "The database admin account username."
    MaxLength: "16"
    MinLength: "1"
    Type: String
  DBMasterUserPassword:
    AllowedPattern: >-
      ^(?=^.{8,255}$)(?=.*[a-z])(?=.*[A-Z])(?=.*\d)((?=.*[^A-Za-z0-9])(?!.*[@/"'])).*$
    ConstraintDescription: >-
      Min 8 chars. Must include 1 uppercase, 1 lowercase, 1 number, 1 (non / @ " ') symbol
    Description: "The database admin account password."
    MaxLength: "64"
    MinLength: "8"
    NoEcho: "True"
    Type: String
  DBPort:
    Default: 5432
    Description: "The port the instance will listen for connections on."
    Type: Number
    ConstraintDescription: 'Must be in the range [1115-65535].'
    MinValue: 1150
    MaxValue: 65535

# Object Storage Parameters
  ObjectStorageSSEAlgorithm:
    Type: String
    Default: AES256
    AllowedValues: [ 'AES256', 'aws:kms' ]
  ObjectStorageKMSMasterKeyID:
    Type: String
    Default: none

# GitLab Parameters
  HelmChartName:
    Type: String
    Default: gitlab
    Description: Name of Helm GitLab deployment.
  HelmChartNamespace:
    Type: String
    Default: default
    Description: Kubernetes namespace to deploy GitLab chart to.
  HelmChartVersion:
    Type: String
    Default: '4.5.1'
  BackupSchedule:
    Type: String
    Default: '0 1 * * *'
  NumberOfGitalyReplicas:
    Type: Number
    Description: Number of Availability Zones to use in the VPC. This must match your
      selections in the list of Availability Zones parameter.

Conditions:
  UsingDefaultBucket: !Equals [!Ref QSS3BucketName, 'aws-quickstart']
  # RealDomainNameProvided: !Equals [!Ref RealDomainName, 'Yes']

Resources:

  Telemetry: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/workload/gitlab-telemetry-template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters: 
        ClusterName: !Ref KubeClusterName

  Infrastructure:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/workload/gitlab-infra-template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        VPCID: !Ref VPCID
        DBPort: !Ref DBPort
        DBAccessCIDR: !Ref VPCCIDR
        DomainName: !Ref DomainName
        CreateHostedZone: !Ref CreateHostedZone
        CreateEmailDomain: !Ref CreateEmailDomain
        CreateSslCertificate: !Ref CreateSslCertificate
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix
        QSS3BucketRegion: !Ref QSS3BucketRegion

  Database:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}submodules/quickstart-amazon-aurora-postgresql/templates/aurora_postgres.template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        DBEngineVersion: 11.7 # GitLab requires >= 11
        DBName: !Ref DBName
        DBMasterUsername: !Ref DBMasterUsername
        DBMasterUserPassword: !Ref DBMasterUserPassword
        DBPort: !Ref DBPort
        VPCID: !Ref VPCID
        Subnet1ID: !Ref PrivateSubnet1ID
        Subnet2ID: !Ref PrivateSubnet2ID
        CustomDBSecurityGroup: !GetAtt Infrastructure.Outputs.DatabaseSecurityGroupID

  PraefectDatabase:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/workload/gitlab-praefect-template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        DBHost: !GetAtt Database.Outputs.RDSEndPointAddress
        DBName: !Ref DBPraefectName
        DBMasterUsername: !Ref DBMasterUsername
        DBMasterUserPassword: !Ref DBMasterUserPassword
        DBPrivateSubnet1ID: !Ref PrivateSubnet1ID
        DBPrivateSubnet2ID: !Ref PrivateSubnet2ID
        DBSecurityGroup: !GetAtt Infrastructure.Outputs.DatabaseSecurityGroupID
        QSS3BucketName: !Ref QSS3BucketName
        QSS3KeyPrefix: !Ref QSS3KeyPrefix

  ObjectStorage:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/workload/gitlab-storage-template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        SSEAlgorithm: !Ref ObjectStorageSSEAlgorithm
        KMSMasterKeyID: !Ref ObjectStorageKMSMasterKeyID

  KubeSecrets:
    Type: AWS::CloudFormation::Stack
    DependsOn: Database
    Properties:
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/workload/gitlab-secrets-template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters:
        KubeClusterName: !Ref KubeClusterName
        HelmChartNamespace: !Ref HelmChartNamespace
        DatabasePassword: !Ref DBMasterUserPassword
        StorageAccessKeyId: !Sub "{{resolve:secretsmanager:${ObjectStorage.Outputs.CredentialsSecretName}:SecretString:accessKeyId}}"
        StorageSecretAccessKey: !Sub "{{resolve:secretsmanager:${ObjectStorage.Outputs.CredentialsSecretName}:SecretString:secretAccessKey}}"
        RegistryBucket: !GetAtt ObjectStorage.Outputs.RegistryBucket

  Chart:
    Type: AWSQS::Kubernetes::Helm   
    DependsOn: PraefectDatabase
    # E3001 Invalid or unsupported Type AWSQS::Kubernetes::Helm
    Metadata: { cfn-lint: { config: { ignore_checks: [E3001] } } }
    Properties:
      ClusterID: !Ref KubeClusterName 
      Namespace: !Ref HelmChartNamespace
      Repository: https://charts.gitlab.io/
      Chart: gitlab/gitlab 
      Name: !Ref HelmChartName
      Version: !Ref HelmChartVersion
      Values:
        certmanager-issuer.email: kolomiets@gmail.com
        # certmanager.install: false

        # domain name
        global.hosts.domain: !Ref DomainName

        # runner configuration
        gitlab-runner.install: false

        # database configuration
        postgresql.install: false
        global.psql.host: !GetAtt Database.Outputs.RDSEndPointAddress
        global.psql.database: !Ref DBName
        global.psql.username: !Ref DBMasterUsername
        global.psql.password.secret: !GetAtt KubeSecrets.Outputs.DatabaseKubeSecretName
        global.psql.password.key: !GetAtt KubeSecrets.Outputs.DatabaseSecretKey

        # Gitaly configuration
        global.praefect.enabled: true
        global.praefect.gitalyReplicas: !Ref NumberOfGitalyReplicas
        global.praefect.dbSecret.secret: !GetAtt KubeSecrets.Outputs.DatabaseKubeSecretName
        global.praefect.dbSecret.key: !GetAtt KubeSecrets.Outputs.DatabaseSecretKey
        global.praefect.psql.host: !GetAtt Database.Outputs.RDSEndPointAddress
        global.praefect.psql.user: !Ref DBMasterUsername
        global.praefect.psql.dbName: !Ref DBPraefectName

        # S3 storage configuration
        ## object storage
        global.minio.enabled: false
        global.appConfig.object_store.enabled: true
        global.appConfig.object_store.proxy_download: true
        global.appConfig.object_store.storage_options.server_side_encryption: AES256
        global.appConfig.object_store.connection.secret: !GetAtt KubeSecrets.Outputs.ObjectStorageKubeSecretName
        global.appConfig.object_store.connection.key: !GetAtt KubeSecrets.Outputs.ConnectionSecretKey
        global.appConfig.artifacts.bucket: !GetAtt ObjectStorage.Outputs.ArtifactsBucket
        global.appConfig.lfs.bucket: !GetAtt ObjectStorage.Outputs.LfsBucket
        global.appConfig.uploads.bucket: !GetAtt ObjectStorage.Outputs.UploadsBucket
        global.appConfig.packages.bucket: !GetAtt ObjectStorage.Outputs.PackagesBucket
        global.appConfig.terraformState.bucket: !GetAtt ObjectStorage.Outputs.TerraformBucket
        global.appConfig.pseudonymizer.bucket: !GetAtt ObjectStorage.Outputs.PseudonymizerBucket
        global.appConfig.backups.bucket: !GetAtt ObjectStorage.Outputs.BuckupBucket
        global.appConfig.backups.tmpBucket: !GetAtt ObjectStorage.Outputs.BuckupTempBucket
        ## registry
        global.registry.bucket: !GetAtt ObjectStorage.Outputs.RegistryBucket
        registry.storage.secret: !GetAtt KubeSecrets.Outputs.ObjectStorageKubeSecretName
        registry.storage.key: !GetAtt KubeSecrets.Outputs.RegistrySecretKey

        # backups, see https://docs.gitlab.com/charts/backup-restore/backup.html
        gitlab.task-runner.backups.cron.enabled: true
        gitlab.task-runner.backups.cron.schedule: !Sub '${BackupSchedule}'
        gitlab.task-runner.backups.objectStorage.config.secret: !GetAtt KubeSecrets.Outputs.ObjectStorageKubeSecretName
        gitlab.task-runner.backups.objectStorage.config.key: !GetAtt KubeSecrets.Outputs.BackupSecretKey


  PostInstall: 
    Type: AWS::CloudFormation::Stack
    Properties: 
      TemplateURL: !Sub
        - 'https://${S3Bucket}.s3.${S3Region}.${AWS::URLSuffix}/${QSS3KeyPrefix}templates/workload/gitlab-postinstall-template.yaml'
        - S3Region: !If [UsingDefaultBucket, !Ref 'AWS::Region', !Ref QSS3BucketRegion]
          S3Bucket: !If [UsingDefaultBucket, !Sub '${QSS3BucketName}-${AWS::Region}', !Ref QSS3BucketName]
      Parameters: 
        ClusterName: !Ref KubeClusterName