AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Gitlab Kubernetes secrets
Parameters:
  KubeClusterName:
    Type: String
  HelmChartNamespace:
    Type: String
    Description: Kubernetes namespace to deploy GitLab chart to.

  DatabasePassword:
    Type: String
    NoEcho: true
  StorageAccessKeyId:
    Type: String
    NoEcho: true
  StorageSecretAccessKey:
    Type: String
    NoEcho: true
  SmtpPassword:
    Type: String
    NoEcho: true

  RegistryBucket:
    Type: String

  DatabaseKubeSecretName:
    Type: String
    Default: quickstart-gitlab-database-secret
  DatabaseSecretKey:
    Type: String
    Default: password

  ObjectStorageKubeSecretName:
    Type: String
    Default: quickstart-gitlab-storage-secret
  ConnectionSecretKey:
    Type: String
    Default: connection
  RegistrySecretKey:
    Type: String
    Default: registry
  BackupSecretKey:
    Type: String
    Default: backup

  SmtpSecretName:
    Type: String
    Default: quickstart-gitlab-smtp-secret
  SmtpSecretKey:
    Type: String
    Default: password

Conditions:
  SmtpEnabled: !Not [!Equals [!Ref SmtpPassword, '']]

Resources:

  DatabaseSecret:
    Type: AWSQS::Kubernetes::Resource
    # E3001 Invalid or unsupported Type AWSQS::Kubernetes::Helm
    Metadata: { cfn-lint: { config: { ignore_checks: [E3001] } } }
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: !Ref HelmChartNamespace
      Manifest: !Sub
        - |
          apiVersion: v1
          data:
            ${SecretKey}: ${EncodedPassword}
          kind: Secret
          metadata:
            name: ${SecretName}
            namespace: ${SecretNamespace}
          type: Opaque
        - SecretNamespace: !Ref HelmChartNamespace
          SecretName: !Ref DatabaseKubeSecretName
          SecretKey: !Ref DatabaseSecretKey
          EncodedPassword:
            Fn::Base64: !Ref DatabasePassword

  ObjectStorageSecret:
    Type: AWSQS::Kubernetes::Resource
    # E3001 Invalid or unsupported Type AWSQS::Kubernetes::Helm
    Metadata: { cfn-lint: { config: { ignore_checks: [E3001] } } }
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: !Ref HelmChartNamespace
      Manifest: !Sub
        - |
          apiVersion: v1
          data:
            ${ConnectionSecretKey}: ${EncodedConnectionSecret}
            ${RegistrySecretKey}: ${EncodedRegitsrySecret}
            ${BackupSecretKey}: ${EncodedBackupSecret}
          kind: Secret
          type: Opaque
          metadata:
            name: ${SecretName}
            namespace: ${SecretNamespace}
        - SecretName: !Ref ObjectStorageKubeSecretName
          SecretNamespace: !Ref HelmChartNamespace
          ConnectionSecretKey: !Ref ConnectionSecretKey
          RegistrySecretKey: !Ref RegistrySecretKey
          BackupSecretKey: !Ref BackupSecretKey
          EncodedConnectionSecret: 
            # see https://docs.gitlab.com/charts/advanced/external-object-storage/#lfs-artifacts-uploads-packages-external-diffs-pseudonymizer-terraform-state-dependency-proxy
            Fn::Base64:
              Fn::Sub: |
                provider: AWS
                region: ${AWS::Region}
                aws_access_key_id: ${StorageAccessKeyId}
                aws_secret_access_key: ${StorageSecretAccessKey}
          EncodedRegitsrySecret:
            # see https://docs.gitlab.com/charts/advanced/external-object-storage/#docker-registry-images
            Fn::Base64:
              Fn::Sub: |
                s3:
                  bucket: ${RegistryBucket}
                  accesskey: ${StorageAccessKeyId}
                  secretkey: ${StorageSecretAccessKey}
                  region: ${AWS::Region}
                  encrypt: true
                  secure: true
                  v4auth: true  
          EncodedBackupSecret:          
            # see https://docs.gitlab.com/charts/advanced/external-object-storage/#backups        
            Fn::Base64:
              Fn::Sub: |
                [default]
                access_key = ${StorageAccessKeyId}
                secret_key = ${StorageSecretAccessKey}
                bucket_location = ${AWS::Region}
                multipart_chunk_size_mb = 128
                server_side_encryption = True                        

  SmtpSecret:
    Type: AWSQS::Kubernetes::Resource
    Condition: SmtpEnabled
    # E3001 Invalid or unsupported Type AWSQS::Kubernetes::Resource
    Metadata: { cfn-lint: { config: { ignore_checks: [E3001] } } }
    Properties:
      ClusterName: !Ref KubeClusterName
      Namespace: !Ref HelmChartNamespace
      Manifest: !Sub
        - |
          apiVersion: v1
          data:
            ${SecretKey}: ${EncodedPassword}
          kind: Secret
          metadata:
            name: ${SecretName}
            namespace: ${SecretNamespace}
          type: Opaque
        - SecretNamespace: !Ref HelmChartNamespace
          SecretName: !Ref SmtpSecretName
          SecretKey: !Ref SmtpSecretKey
          EncodedPassword:
            Fn::Base64: !Ref SmtpPassword

Outputs:
  DatabaseKubeSecretName:
    Value: !Ref DatabaseKubeSecretName
  DatabaseSecretKey:
    Value: !Ref DatabaseSecretKey

  ObjectStorageKubeSecretName:
    Value: !Ref ObjectStorageKubeSecretName
  ConnectionSecretKey:
    Value: !Ref ConnectionSecretKey
  RegistrySecretKey:
    Value: !Ref RegistrySecretKey
  BackupSecretKey:
    Value: !Ref BackupSecretKey

  SmtpSecretName:
    Value: !Ref SmtpSecretName
  SmtpSecretKey:
    Value: !Ref SmtpSecretKey